steps:

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA',
    '-f', 'Dockerfile',
    '.'
  ]
  timeout: 1200s

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', '$_IMAGE_NAME',
    '--image=gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA',
    '--cpu=2', '--memory=4Gi',
    '--region=us-central1',
    '--service-account=$SERVICE_ACCOUNT_EMAIL', # Directly use the substitution variable
    '--set-env-vars=PROJECT_ID=$PROJECT_ID,COMMIT_SHA=$COMMIT_SHA',ARTIFACT_GCS_BUCKET=$_ARTIFACT_GCS_BUCKET,
    '--concurrency=1',
    '--timeout=3600',
    '--execution-environment=gen2',
  ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$COMMIT_SHA'