import logging
from google.cloud import bigquery
import bq_utils 
import str_utils

def compose_coalesced_outer_join_query(project: str, dataset: str, table_v1: str, table_v2: str) -> str:
    """
    Generates a SQL query that performs a FULL OUTER JOIN between two BigQuery tables, 
    coalescing common columns while retaining unique columns from each table.

    Args:
        project  (str): The Google Cloud project ID.
        dataset  (str): The BigQuery dataset containing the tables.
        table_v1 (str): The name of the first table (e.g.,  'module1_v1_JP').
        table_v2 (str): The name of the second table (e.g., 'module1_v2_JP').

    Returns:
        str: A dynamically generated SQL query string.
    """
    
    if not all([project, dataset, table_v1, table_v2]):
        raise ValueError("Project, dataset, table_v1, and table_v2 must be non-empty strings.")
    
    client = bigquery.Client(project=project)

    v1_columns = bq_utils.get_column_names(client, project, dataset, table_v1)
    v2_columns = bq_utils.get_column_names(client, project, dataset, table_v2)

    if not v1_columns and not v2_columns:
        logging.error("No columns retrieved from either table. Exiting.")
        return ""

    # Identify common and unique columns
    common_columns = v1_columns & v2_columns
    v1_unique_columns = v1_columns - v2_columns
    v2_unique_columns = v2_columns - v1_columns

    # Construct SELECT clause dynamically
    select_clauses = []

    # Add section for coalesced columns
    if common_columns:
        select_clauses.append("-- Coalesced common columns")
        for col in sorted(common_columns):
            select_clauses.append(f"COALESCE(v2.{col}, v1.{col}) AS {col}")

    # Add section for unique columns from table_v1
    if v1_unique_columns:
        select_clauses.append("-- Unique columns from table_v1")
        for col in sorted(v1_unique_columns):
            select_clauses.append(f"v1.{col}")

    # Add section for unique columns from table_v2
    if v2_unique_columns:
        select_clauses.append("-- Unique columns from table_v2")
        for col in sorted(v2_unique_columns):
            select_clauses.append(f"v2.{col}")

    # Generate the final SQL query
    query = f"""
    -- Autogenerated query for PR2 Pipeline.
    -- Objectives:
    -- + Merge {table_v1} and {table_v2}.
    -- + If variables exist in both {table_v1} and {table_v2}, use value from {table_v2}.
    -- + Ensure that variables that are unique either to {table_v1} or to {table_v2} are retained.
    
    SELECT
        {",\n        ".join(select_clauses)}
    FROM
        `{project}.{dataset}.{table_v2}` v2
    FULL OUTER JOIN
        `{project}.{dataset}.{table_v1}` v1
    ON
        v1.Connect_ID = v2.Connect_ID
    """

    return query

def compose_coalesce_loop_variable_query(project, dataset, table) -> str:
    """
    Generates a SQL query to coalesce multiple versions of loop variables.

    This function assumes all variable names are **pure**, meaning they contain only:
        - A **"D" (or "d")** prefix.
        - A **9-digit concept ID**.
        - A **single-digit loop number**.

    If a variable does not meet these conditions, a `ValueError` is raised.

    **How It Works**:
    - Groups of variables are processed to extract their **ordered concept IDs**.
    - A new alias is constructed using these IDs.

    **Example**:
        Given the first variable in a group:
        ```plaintext
        D_812370563_1_1_D_812370563_1_1_D_665036297
        ```
        The extracted concept IDs:
        ```plaintext
        ['812370563', '812370563', '665036297']
        ```
        The generated alias:
        ```plaintext
        d_812370563_d_812370563_d_665036297_1
        ```

    Args:
        project (str): The Google Cloud project ID.
        dataset (str): The BigQuery dataset containing the table.
        table (str): The name of the table (e.g., 'module1_v1_JP').

    Returns:
        str: A dynamically generated SQL query string.

    Raises:
        ValueError: If any variable name is not pure.
    """
    # Connect to BigQuery
    client = bigquery.Client(project=project)
    
    # Retrieve all variable names from the table.
    variables = bq_utils.get_column_names(client, project, dataset, table)
    
    # Assert that all variables are pure.
    for var in variables:
        if not str_utils.is_pure_variable(var):
            raise ValueError(f"Variable '{var}' is not pure. Please pre-process exceptions before composing the query.")
    
    # Group pure variables by concept IDs and loop number.
    grouped_loop_vars = str_utils.group_vars_by_cid_and_loop_num(variables)
    
    select_clauses = []
    for key, var_list in grouped_loop_vars.items():
        loop_number = key[1]
        first_var = var_list[0]
        ordered_ids = str_utils.extract_ordered_concept_ids(first_var)
        # Build the new alias preserving order:
        new_var_name = "_".join(f"d_{cid}" for cid in ordered_ids) + f"_{loop_number}"
        
        # Construct the SELECT clause:
        if len(var_list) == 1:
            clause = f"{var_list[0]} AS {new_var_name}"
        else:
            clause = f"COALESCE({', '.join(var_list)}) AS {new_var_name}"
        select_clauses.append((new_var_name, clause))
    
    # Order the select clauses by the alias
    sorted_clauses = sorted(select_clauses, key=lambda x: x[0])
    select_clause_strs = [clause for _, clause in sorted_clauses]
    
    # Build the final SQL query.
    query = f"""
    -- Autogenerated query for coalescing loop variables
    SELECT
        Connect_ID,
        {",\n        ".join(select_clause_strs)}
    FROM `{project}.{dataset}.{table}`
    """.strip()
    
    return query

if __name__ == "__main__":
    
    project = "nih-nci-dceg-connect-prod-6d04"
    dataset = "FlatConnect"
    output_dir = 'sql'
    
    # Coalesce Loop Variables =========================================================================
    if True:
        tables = ["module1_v1_JP", "module1_v2_JP", "module2_v1_JP", "module2_v2_JP"]
        for table in tables:
            
            file_name = f"coalesce_and_rename_loops_for_{table}.sql"
            coalesce_loop_var_query = compose_coalesce_loop_variable_query(project, dataset, table)
            
            # Write the query to a file (correct indentation)
            with open(f"{output_dir}/{file_name}", "w") as file:
                file.write(coalesce_loop_var_query)
                
            #print(coalesce_loop_var_query)
        
    # Join Module 1 Versions ===========================================================================
    
    if True:
        table_v1 = "module1_v1_JP"
        table_v2 = "module1_v2_JP"
        file_name = "merge_module1.sql"

        sql_query = compose_coalesced_outer_join_query(project, dataset, table_v1, table_v2)

        # Write the query to a file (correct indentation)
        with open(f"{output_dir}/{file_name}", "w") as file:
            file.write(sql_query)

        print(f"SQL query has been saved to {file_name}")
        
    if True:
        dataset = "ForTestingOnly"
        table_v1 = "coalesced_module1_v1"
        table_v2 = "coalesced_module1_v2"
        file_name = "merge_module1.sql"

        sql_query = compose_coalesced_outer_join_query(project, dataset, table_v1, table_v2)

        # Write the query to a file (correct indentation)
        with open(f"{output_dir}/{file_name}", "w") as file:
            file.write(sql_query)

        print(f"SQL query has been saved to {file_name}")
    
    
    # Join Module 2 Versions ===========================================================================
    if True:
        table_v1 = "module2_v1_JP"
        table_v2 = "module2_v2_JP"
        file_name = "merge_module2.sql"

        sql_query = compose_coalesced_outer_join_query(project, dataset, table_v1, table_v2)

        # Write the query to a file (correct indentation)
        with open(f"{output_dir}/{file_name}", "w") as file:
            file.write(sql_query)

        print(f"SQL query has been saved to {file_name}")